=== usurakod/XML-schema/buildings.xsd
<?xml version="1.0" encoding="UTF-8"?>
   <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified">
   <xs:element name="address">
       <xs:complexType>
       		<xs:sequence>
       			<xs:element name="StreetNo" type="xs:integer"/>
       			<xs:element name="StrName" type="xs:string"/>
       			<xs:element name="City" type="xs:string"/>
       			<xs:element name="State" type="xs:string"/>
       			<xs:element name="Zip" type="xs:integer"/>
       		</xs:sequence>
       	</xs:complexType>
   </xs:element>
   <xs:element name="position">
   		<xs:complexType>
   			<xs:all>
   			<xs:element name="Lat" type="xs:string"/>
   			<xs:element name="Long" type="xs:string"/>
   			</xs:all>
   		</xs:complexType>
   </xs:element>
   <xs:element name="buildingCode">
   	  <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:pattern value="\s*[a-z|A-Z]{3}\s*"/>
        </xs:restriction>
      </xs:simpleType>
   </xs:element>
   <xs:element name="building">
   		<xs:complexType>
   			<xs:sequence>
   				<xs:element ref="buildingCode"/>
   				<xs:element name="buildingName" type="xs:string"/>
   				<xs:element ref="position"/>
   				<xs:element ref="address" maxOccurs="1" minOccurs="0"/>
   			</xs:sequence>
   		</xs:complexType>
   </xs:element>
   <xs:element name="buildings">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="building" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== usurakod/XML-schema/buildings.xml
<?xml version="1.0" encoding="UTF-8"?>
<buildings   xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
             xsi:noNamespaceSchemaLocation='buildings.xsd'>
    <building>
        <buildingCode>KOH</buildingCode>
        <buildingName>King Olympic Hall</buildingName>
        <position>
            <Lat>34.024547</Lat>
            <Long> -118.288 </Long>
        </position>
        <address>
            <StreetNo>1027</StreetNo>
            <StrName>W 34th St</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90007</Zip>
        </address>
    </building>
    
     <building>
        <buildingCode>CFX</buildingCode>
        <buildingName> Cromwell Field</buildingName>
        <position>
            <Lat>34.021631</Lat>
            <Long> -118.289 </Long>
        </position>
        <address>
            <StreetNo>1026</StreetNo>
            <StrName>W 34th St</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90089</Zip>
        </address>
    </building>
    
    
     <building>
        <buildingCode>JEP</buildingCode>
        <buildingName> JEP House</buildingName>
        <position>
            <Lat>34.022947</Lat>
            <Long>-118.284</Long>
        </position>
        <address>
            <StreetNo> 801 </StreetNo>
            <StrName>W 34th St</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90089</Zip>
        </address>
    </building>
    
     <building>
        <buildingCode>SHC</buildingCode>
        <buildingName> Student Health Center </buildingName>
        <position>
            <Lat>34.023303</Lat>
            <Long>-118.285 </Long>
        </position>
        <address>
            <StreetNo> 849 </StreetNo>
            <StrName>W 34th St</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90089</Zip>
        </address>
    </building>
    
     <building>
        <buildingCode>LVY</buildingCode>
        <buildingName> Leavey Library </buildingName>
        <position>
            <Lat>34.021595</Lat>
            <Long>-118.282</Long>
        </position>
        <address>
            <StreetNo> 651 </StreetNo>
            <StrName>W 35th St</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90089</Zip>
        </address>
    </building>
    
    <building>
        <buildingCode>VKC</buildingCode>
        <buildingName> Von KleinSmid Center </buildingName>
        <position>
            <Lat>34.021649</Lat>
            <Long>-118.284</Long>
        </position>
        <address>
            <StreetNo> 3518 </StreetNo>
            <StrName>Trousdale</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90089</Zip>
        </address>
    </building>
    <building>
        <buildingCode>WPH</buildingCode>
        <buildingName> Waite Phillips Hall</buildingName>
        <position>
            <Lat>34.022289</Lat>
            <Long>-118.284</Long>
        </position>
        <address>
            <StreetNo> 3550 </StreetNo>
            <StrName>Trousdale</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90089</Zip>
        </address>
    </building>
    
     <building>
        <buildingCode>JHH</buildingCode>
        <buildingName> John Hubbard Hall </buildingName>
        <position>
            <Lat>34.020101</Lat>
            <Long>-118.284</Long>
        </position>
        <address>
            <StreetNo> 615 </StreetNo>
            <StrName>ChildsWay</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90089</Zip>
        </address>
    </building>
    
     <building>
        <buildingCode>REG</buildingCode>
        <buildingName> Registration Builing</buildingName>
        <position>
            <Lat>34.019603</Lat>
            <Long>-118.282</Long>
        </position>
        <address>
            <StreetNo> 611 </StreetNo>
            <StrName>ChildsWay</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90089</Zip>
        </address>
    </building>
    
    <building>
        <buildingCode>STU</buildingCode>
        <buildingName> Student Union </buildingName>
        <position>
            <Lat>34.020226</Lat>
            <Long>-118.286</Long>
        </position>
        <address>
            <StreetNo> 3551 </StreetNo>
            <StrName>Trousdale</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90089</Zip>
        </address>
    </building>
    
    <building>
        <buildingCode>BKS</buildingCode>
        <buildingName> Bookstore </buildingName>
        <position>
            <Lat>34.020635</Lat>
            <Long>-118.286</Long>
        </position>
        <address>
            <StreetNo> 840 </StreetNo>
            <StrName>ChildsWay</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90089</Zip>
        </address>
    </building>
    
    <building>
        <buildingCode>RTH</buildingCode>
        <buildingName> Ronald Tutor Hall </buildingName>
        <position>
            <Lat>34.020137</Lat>
            <Long>-118.29</Long>
        </position>
        <address>
            <StreetNo> 3710 </StreetNo>
            <StrName>McClintock</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90089</Zip>
        </address>
    </building>
    
    <building>
        <buildingCode>SAL</buildingCode>
        <buildingName>Salvatori Com. Center</buildingName>
        <position>
            <Lat>34.01955</Lat>
            <Long>-118.289</Long>
        </position>
        <address>
            <StreetNo> 941 </StreetNo>
            <StrName> W 37th Place</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90089</Zip>
        </address>
    </building>
    
    <building>
        <buildingCode>EEB</buildingCode>
        <buildingName>Electrical Engr Center</buildingName>
        <position>
            <Lat>34.019728</Lat>
            <Long>-118.29</Long>
        </position>
        <address>
            <StreetNo> 3715 </StreetNo>
            <StrName> McClintock</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90089</Zip>
        </address>
    </building>
    
    
     <building>
        <buildingCode>OHE</buildingCode>
        <buildingName>Olin Hall Engineering</buildingName>
        <position>
            <Lat>34.020493</Lat>
            <Long>-118.29</Long>
        </position>
        <address>
            <StreetNo> 3650 </StreetNo>
            <StrName> McClintock</StrName>
            <City>Los Angeles</City>
            <State>CA</State>
            <Zip>90089</Zip>
        </address>
    </building>
    
 
   
    
   
</buildings>
